server:
  port: 8899
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sameway?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    com.bzdnet.sameway.dao: debug
    com.bzdnet.sameway.mapper: debug
mybatis-plus:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: false

interceptor:
  auth:
    exclude-login-list:
      - /auth/user/login
    exclude-auth-list:
      - /auth/user/logout
      - /auth/user/current
      - /auth/user/current/menu
      - /auth/user/current/func
